### ISSUE TITLE
logo design contribution

### ISSUE THREAD

**Issue by masudr4n4** [hexian000/MassTransfer#1]
hey
i want to make a logo for this projects if you have any requirements then let me know.its totally free for open source projects.

**Comment by hexian000** [comment]
Wow cool! I have no requirements. I will be happy if it can have a logo.

发送自 Windows 10 版邮件应用

发件人: Md Masud Rana
发送时间: 2018年5月21日 21:41
收件人: hexian000/MassTransfer
抄送: Subscribed
主题: [hexian000/MassTransfer] logo design contribution (#1)

hey
i want to make a logo for this projects if you have any requirements then let me know.its totally free for open source projects.

**Comment by masudr4n4** [comment]
![masstransfer-01](https://user-images.githubusercontent.com/34313493/40386277-0f93ec0c-5e2b-11e8-890e-be0da2596bc1.jpg)

If you like this i will open a pull request for using this in app.

thank you

**Comment by hexian000** [comment]
Good job! The simple idea just fits this app well.
just go ahead to create a pull request

**Comment by masudr4n4** [comment]
please check pull #2

**Comment by hexian000** [comment]
Thanks for your contribution!
can i use this image as the app icon too?

**Comment by masudr4n4** [comment]
Yes.of course 
I am making the editable file of the logo.
Please wait.

**Comment by masudr4n4** [comment]
You can download now all the editable file of the logo.
Just click
<a href="https://drive.google.com/drive/folders/1wqqsOhzrMzRUIvqhzXgg25Bl-t1biLh8?usp=sharing"> Download</a>

<a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>

**Comment by hexian000** [comment]
I created a new release with icon. Now it looks better than before.
Great works~
